[[redirects]]
  from = "/info/why"
  to = "/en/why"
  force = true

[[redirects]]
  from = "/info/how"
  to = "/en/how"
  force = true

[[redirects]]
  from = "/info/resources"
  to = "/en/resources"
  force = true

# Redirect any URLs with the language code in them already
[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 301
  force = true

# Important: Per shadowing rules, URLs for the
# _non-default_ language-specific content files
# are served without redirects.

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/es/:splat"
  status = 302
  conditions = {Language = ["es"]}

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/zh/:splat"
  status = 302
  conditions = {Language = ["zh"]}

# Default
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
