# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests with Node.js 12.19.0
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.0
    - run: npm install
    - run: npm run prod
    - run: npm test
